---
swagger: '2.0'
info:
  title: Gerrit data source
  version: '1.0'
  description: Gerrit data source V2
paths:    # swagger forces me to add at least one path
  /noop:
    get:
      description: no-op
      responses:
        200:
          description: ok
definitions:
  DataSource:
    type: object
    properties:
      Slug:
        type: string
        example: gerrit
      Name:
        type: string
        example: Gerrit
  MetaData:
    type: object
    properties:
      BackendName:
        type: string
        example: insights-datasource-gerrit
      BackendVersion:
        type: string
        example: v0.1.0
      Project:
        type: string
        example: Hyperledger Sawtooth
      Tags:
        type: array
        items:
          type: string
          example: my-tag
  Identity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      Name:
        type: string
        example: Lukasz Gryglicki
      Username:
        type: string
        example: lgryglicki
      Email:
        type: string
        example: xyz@abc.com
      DataSourceId:
        type: string
        example: gerrit
        description: data source type slug (FK)
  CodeChangeRequestCommit:
    type: object
    properties:
      SHA:
        type: string
        example: 2b20505d9d60202c6779342033d344dba0685d1b
      Author:
        type: object
        description: committer
        $ref: "#/definitions/Identity"
      Committer:
        type: object
        description: committer
        $ref: "#/definitions/Identity"
  CodeChangeRequestActivity:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      CodeChangeRequestKey:
        type: string
        example: 1234567890abcdef
        description: FK - up to 50 chars, points to CodeChangeRequest.Id
      CodeChangeRequestId:
        type: string
        example: 1234567890abcdef
        description: points to CodeChangeRequest.CodeChangeRequestId 
      CreatedAt:
        type: string
        format: date-time
        example: '2019-09-02 03:00:33.000000'
      ActivityType:
        type: string
        example: unknown yet (gerrit_changeset_created, gerrit_comment_added, gerrit_approval_added), note that approval can be approving or rejecting, approved when state >= 0
        description: allows reconstructing relations
      Body:
        type: string
        description: changeset/patchset/approval body
        example: My comment body
        x-nullable: true
      URL:
        type: string
        description: changeset/patchset/approval URL
        x-nullable: true
      Key:
        type: string
        description: may be needed to reconstruct gerrit structures (this is Gerrit comment ID, patchset ID, changeset ID)
        example: "150"
        x-nullable: true
      State:
        type: integer
        x-nullable: true
        example: 1
        description: only present if activity type is a review, >= 0 means approved
      IsApproval:
        type: boolean
        x-nullable: true
        example: true, false, null
        description: only present if activity type is an approval (doesn't mean approved, you need to check state >= 0)
      Identity:
        type: object
        description: activity creator (ProjectDataSourceIdentity)
        $ref: "#/definitions/Identity"
  CodeChangeRequest:
    type: object
    properties:
      Id:
        type: string
        example: 1234567890abcdef
        description: PK - up to 50 chars
      CodeChangeRequestId:
        type: string
        example: 1234567890abcdef
        description: Gerrit internal changeset/review ID (git hash)
      CodeChangeRequestNumber:
        type: string
        example: 1234567890abcdef
        description: Gerrit internal changeset number
      CreatedAt:
        type: string
        format: date-time
      UpdatedAt:
        type: string
        format: date-time
        example: '2019-09-02 03:00:33.000000'
      ClosedAt:
        type: string
        format: date-time
        x-nullable: true
      IsClosed:
        type: boolean
        example: false
      MergedAt:
        type: string
        format: date-time
        x-nullable: true
      IsMerged:
        type: boolean
        example: false
      State:
        type: string
        example: NEW, MERGED, ABANDONED
      Title:
        type: string
        example: My PR title
      DataSourceId:
        type: string
        example: gerrit
        description: data source type slug (FK)
      Activities:
        type: array
        items:
          $ref: "#/definitions/CodeChangeRequestActivity"
      Commits:
        type: array
        items:
          $ref: "#/definitions/CodeChangeRequestCommit"
  Event:
    type: object
    description: single event in gerrit is a review/changeset (which is an activity on CodeChangeRequest), it contains comments and patchsets, a patchset contains approvals
    properties:
      CodeChangeRequest:
        type: object
        x-nullable: true
        $ref: "#/definitions/CodeChangeRequest"
  Data:
    type: object
    description: this is the final output of insights-datasource-gerrit, data source will output packs up to some fixed size, like 500 events pack at once
    properties:
      DataSource:
        type: object
        $ref: "#/definitions/DataSource"
      MetaData:
        type: object
        $ref: "#/definitions/MetaData"
      Endpoint:
        type: string
        description: Gerrit endpoint for which data is being sent
        example: gerrit.onap.org
      Events:
        type: array
        items:
          $ref: "#/definitions/Event"
